// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabeWrS1e1xMxdZb7ldDOEmhgo1eC-tL0',
    appId: '1:983363796447:web:ccb729e30683eb42fbd86a',
    messagingSenderId: '983363796447',
    projectId: 'mygroceryapp-8ab39',
    authDomain: 'mygroceryapp-8ab39.firebaseapp.com',
    storageBucket: 'mygroceryapp-8ab39.appspot.com',
    measurementId: 'G-K4H20B9926',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNW8_TQZxy6ec7t-0cCaYpRhk9AaGFSk',
    appId: '1:983363796447:android:4fcd414eadd2b56dfbd86a',
    messagingSenderId: '983363796447',
    projectId: 'mygroceryapp-8ab39',
    storageBucket: 'mygroceryapp-8ab39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPZqWqFcgpWNB2eY0NLhwNPGSu9PWrPk',
    appId: '1:983363796447:ios:c1acf0935a5017d4fbd86a',
    messagingSenderId: '983363796447',
    projectId: 'mygroceryapp-8ab39',
    storageBucket: 'mygroceryapp-8ab39.appspot.com',
    iosBundleId: 'com.example.myGroceryAdmin',
  );
}
